---
- name: install nodebrew
  command: curl -L git.io/nodebrew | perl - setup

- name: install nodejs from binary
  command: export PATH=$HOME/.nodebrew/current/bin:$PATH && nodebrew install-binary stable
