---
- name: common packages installed
  yum: name={{item}} state=installed
  with_items:
    - git
    - svn
    - wget
    - curl
    - gcc
    - make
    - zsh
    - ctags
    - vixie-cron
    - glances
    - samba
    - perl-ExtUtils-MakeMaker
    - patch
    - unzip
    - expat-devel
  tags: centos-packages

- name: middleware packages installed
  yum: name={{item}} state=installed
  with_items:
    - nginx
    - redis
    - memcached
    - docker-io
  tags: centos-packages

- name: rails packages
  yum: name={{item}} state=installed
  with_items:
    - libxml2-devel
    - openssl-devel
    - libnotify
    - libicu-devel
    - libjpeg-devel
    - libpng-devel
    - ImageMagick
    - ImageMagick-devel
  tags: centos-packages
