---
- name: install perlbrew
  command: curl -L http://xrl.us/perlbrewinstall | bash

- name: install perl {{perl_version}}
  shell: source ~/perl5/perlbrew/etc/bashrc && perlbrew install perl-{{perl_version}}
