---
- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  tags:
    - ruby

- name: install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  tags:
    - ruby

- name: Add ~.rbenv/bin to PATH
  lineinfile: >
    create=yes
    dest="~/.bashrc"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  tags:
    - ruby

- name: Eval rbenv init in ~/.bashrc
  lineinfile: >
    dest="~/.bashrc"
    line='eval "$(rbenv init -)"'
  tags:
    - ruby

- name: "Check if {{ ruby_version }} is installed"
  shell: "rbenv versions | grep {{ ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: True
  tags:
    - ruby

- name: install ruby version {{ ruby_version }}
  shell: rbenv install -v {{ ruby_version }}
  when: rbenv_check_install|failed
  tags:
    - ruby

- name: "Check if {{ ruby_version }} is the default ruby version"
  shell: "rbenv version | grep {{ ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True
  tags:
    - ruby

- name: version specified to be used
  shell: rbenv global {{ ruby_version }}
  when: rbenv_check_default|failed
  tags:
    - ruby

- name: rbenv rehash
  shell: rbenv rehash
  when: rbenv_check_default|failed
  tags:
    - ruby

- name: gem install bundler on rbenv
  gem:
    name=bundler
    version=1.3.0
    state=present
    executable=~/.rbenv/shims/gem
    user_install=no
  tags:
    - ruby
