---
- name: tmux package installed
  yum: name={{item}} state=installed
  with_items:
    - wget
    - gcc
    - make
    - ncurses
    - ncurses-devel
  tags: centos-tmux

- name: download libevent
  shell:  curl -L https://github.com/downloads/libevent/libevent/libevent-{{libevent_version}}.tar.gz -o /var/tmp/libevent-{{libevent_version}}.tar.gz
#  get_url: url=https://github.com/libevent/libevent/archive/release-{{libevent_version}}.tar.gz dest=/var/tmp/libevent-{{libevent_version}}.tar.gz
  tags: centos-tmux

- name: extract libevent
  shell: tar xfC /var/tmp/libevent-{{libevent_version}}.tar.gz /var/tmp/
  tags: centos-tmux

- name: make install libevent
  shell: cd /var/tmp/libevent-{{libevent_version}} && ./configure --prefix=/usr/local && make && sudo make install
  tags: centos-tmux

- name: download tmux
  get_url: url=http://downloads.sourceforge.net/tmux/tmux-{{tmux_version}}.tar.gz dest=/var/tmp/tmux-{{tmux_version}}.tar.gz
  tags: centos-tmux

- name: extract tmux
  shell: tar xfC /var/tmp/tmux-{{tmux_version}}.tar.gz /var/tmp
  tags: centos-tmux

- name: make install tmux
  shell: cd /var/tmp/tmux-{{tmux_version}} && LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local && make && sudo make install
  tags: centos-tmux
